package com.serverless.model;

import com.amazonaws.services.dynamodbv2.datamodeling.*;

public class Product {

    private String id;
    private String name;
    private Float price;


    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
                return this.id;
    }

    public void setId(String id) {
                this.id = id;
    }

    @DynamoDBRangeKey(attributeName = "name")
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @DynamoDBAttribute(attributeName = "price")
    public Float getPrice() {
        return price;
    }

    public void setPrice(Float price) {
        this.price = price;
    }
}
